- name: transformer_cross_attn_kalman_type_1
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: kalman
    ds_type: type_1

- name: transformer_cross_attn_kalman_type_2
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: kalman
    ds_type: type_2

- name: transformer_cross_attn_kalman_type_3
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: kalman
    ds_type: type_3

- name: transformer_cross_attn_no_filter_type_1
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: no_filter
    ds_type: type_1

- name: transformer_cross_attn_no_filter_type_2
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: no_filter
    ds_type: type_2

- name: transformer_cross_attn_no_filter_type_3
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: no_filter
    ds_type: type_3

- name: transformer_cross_attn_kalman_type_4
  skip: False
  optimization:
    epochs: 15
  train:
    epochs: 150
  common:
    use_cuda: None
    filter: kalman
    ds_type: type_4